### ISSUE TITLE
NOT CONNECTING!

### ISSUE THREAD

**Issue by ghost** [SAV-404/Old-agario#3]
![image](https://user-images.githubusercontent.com/30329244/30771320-a2c5500a-a077-11e7-92dc-c6fc59779b51.png)
![image](https://user-images.githubusercontent.com/30329244/30771321-a796b132-a077-11e7-811c-77e8853e9216.png)

**Comment by SAV-404** [comment]
please play on this client https://sav-404.github.io/oldAgario/index.html
