### ISSUE TITLE
Why not work skins in MultiOgar-Edited 1.6.1? I have the solution

### ISSUE THREAD

**Issue by josefredohd** [SAV-404/Old-agario#5]
Enter the file PlayerTracker.js and on the line 116 and replace "writer.writeStringZeroUtf8( skin);" for "writer.writeStringZeroUtf8("%" + skin);"

**Comment by SAV-404** [comment]
hah..and you right...i was trying to fix that..but i'm busy as hell..
thank you man!

**Comment by SAV-404** [comment]
what are you talking about..it's already exist on the oldest and the newest version  of MultiOgar-Edited .

**Comment by SAV-404** [comment]
man...can i contact you??

**Comment by josefredohd** [comment]
My skype is JoseFredoHD

**Comment by SAV-404** [comment]
discord??

**Comment by josefredohd** [comment]
JoseFredoHD#1652
